### ISSUE TITLE
NugComboBarValeera Only One Bar

### ISSUE THREAD

**Issue by CrunchyHotDogs** [rgd87/NugComboBar#5]
Only the first combo bar seems to show up.
I tested it on my mage and I couldn't get a bar to show up for Fireblast.

I didn't get the chance to test it on any other characters.

**Comment by d87** [comment]
That's my bad putting fire blast on the second row.
Skins don't support advanced things like progress bars, rune charges and have problems with 2-row layouts. Which is fine because people who use skins are mostly rogue/paladin mains and they don't care
Anyway, get skin update here
http://www.wowinterface.com/downloads/info24333-NugComboBarValeera.html
and main addon update here
https://raw.githubusercontent.com/rgd87/NugComboBar/5a93b80a5111b7442a652f93a9b88f0fe7ee7eff/NugComboBar.lua
